#!/usr/bin/with-contenv bash

if [[ "${DSMRREADER_REMOTE_DATALOGGER_MODE}" = standalone || "${DSMRREADER_REMOTE_DATALOGGER_MODE}" = receiver ]]; then
    echo "Starting DSMR Reader - webinterface..."
    cd /app || exit
    exec s6-setuidgid app /usr/local/bin/gunicorn dsmrreader.wsgi --timeout 60 --max-requests 500 --bind unix:/var/tmp/gunicorn--dsmr_webinterface.socket
fi
