volumes:
  dsmrdb_data:
  dsmr_backups:

services:

  # ---------------- DSMRDB -----------------
  dsmrdb:
    image: postgres:17-alpine
    container_name: dsmrdb
    restart: always
    networks: [dsmrnet]
    volumes:
      - dsmrdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dsmrreader
      POSTGRES_PASSWORD: dsmrreader
      POSTGRES_DB: dsmrreader

  # ---------------- DSMRDB -----------------
  dsmr:
    image: localhost/dsmr_test_image:latest
    container_name: dsmr
    restart: always
    depends_on:
      - dsmrdb
    networks: [dsmrnet]
    ports:
      - "7980:80"
    volumes:
      - dsmr_backups:/app/backups
    environment:
      DJANGO_TIME_ZONE: Europe/Amsterdam
      ENABLE_VACUUM_DB_ON_STARTUP: true
      DJANGO_DATABASE_NAME: dsmrreader
      DJANGO_DATABASE_HOST: dsmrdb
      DJANGO_DATABASE_USER: dsmrreader
      DJANGO_DATABASE_PASSWORD: dsmrreader
      DJANGO_SECRET_KEY: dsmrreader
      DJANGO_DATABASE_PORT: 5432
      DSMRREADER_ADMIN_USER: admin
      DSMRREADER_ADMIN_PASSWORD: admin
      DSMRREADER_OPERATION_MODE: standalone

networks:
  dsmrnet:
    driver: bridge