volumes:
  dsmrdb_data:
  dsmr_backups:

services:

  # ---------------- DSMRDB -----------------
  dsmrdb:
    image: postgres:17-alpine
    container_name: dsmrdb
    restart: unless-stopped
    networks: [dsmrnet]
    volumes:
      - dsmrdb_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: dsmrreader
      POSTGRES_PASSWORD: dsmrreader
      POSTGRES_DB: dsmrreader
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------------- DSMRDB -----------------
  dsmr:
    image: dsmr_test_image:latest
    container_name: dsmr
    restart: unless-stopped
    depends_on:
      dsmrdb:
        condition: service_healthy
    networks: [dsmrnet]
    ports:
      - "7980:80"
    volumes:
      - dsmr_backups:/app/backups:rw
    environment:
      DJANGO_TIME_ZONE: Europe/Amsterdam
      DJANGO_DATABASE_NAME: dsmrreader
      DJANGO_DATABASE_HOST: dsmrdb
      DJANGO_DATABASE_USER: dsmrreader
      DJANGO_DATABASE_PASSWORD: dsmrreader
      DJANGO_SECRET_KEY: dsmrreader
      DJANGO_DATABASE_PORT: 5432
      # DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:7980,http://127.0.0.1:7980"
      # DJANGO_ALLOWED_HOSTS: "*"
      DSMRREADER_ADMIN_USER: admin
      DSMRREADER_ADMIN_PASSWORD: admin
      CONTAINER_RUN_MODE: standalone
networks:
  dsmrnet:
    driver: bridge
