#!/usr/bin/with-contenv bash

if [[ "${DATALOGGER_MODE}" = standalone || "${DATALOGGER_MODE}" = receiver ]]; then
    echo "Starting DSMR Reader - nginx..."
    cd /dsmr || exit
    exec /usr/sbin/nginx -g 'daemon off;'
fi
