#!/usr/bin/with-contenv bash

if [[ "${DSMRREADER_REMOTE_DATALOGGER_MODE}" = standalone || "${DSMRREADER_REMOTE_DATALOGGER_MODE}" = receiver ]]; then
    echo "Starting DSMR Reader - nginx..."
    cd /app || exit
    exec /usr/sbin/nginx -g 'daemon off;'
else
    sleep infinity
fi
