#!/usr/bin/with-contenv bash

if [[ "${DATALOGGER_MODE}" = standalone || "${DATALOGGER_MODE}" = receiver ]]; then
    echo "Starting DSMR Reader - nginx..."
    cd /app || exit
    exec s6-setuidgid app /usr/sbin/nginx -g 'daemon off;'
fi
