name: 💡 Feature Request
description: Suggest an idea or enhancement for DSMR Reader in Docker.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement! 🎉
        
        > [!WARNING]
        > **Important scope limitations before you submit:**
        > * The main focus of this repository is running **DSMR Reader in Docker**. 
        > * Requests or features related to the core **DSMR Reader** application itself cannot be processed here. Please report those to the upstream project.

  - type: dropdown
    id: language
    attributes:
      label: Language / Voertaal
      description: |
        > [!TIP]
        > *🇬🇧 Unable to communicate in Dutch? Welcome anyway! Feel free to use English.*
        > *🇳🇱 Voel je vooral vrij om in het Nederlands te communiceren, ondanks dat het project Engelstalig is.*
      options:
        - '🇳🇱 Nederlandstalig'
        - '🇬🇧 English'
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: The Problem
      description: Is your feature request related to a specific problem or limitation with the Docker implementation?
      placeholder: "I'm always frustrated when [...] because [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: The Proposed Solution
      description: Describe the feature or enhancement you would like to see implemented. What value does it bring to the users of this Docker image?
      placeholder: "I would like to see a feature that [...]"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: >-
        If you have any additional context, `docker-compose.yml` configuration examples, or alternatives you've considered, add them below. 
        You can attach screenshots or text files by dragging and dropping them into this field.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to ensure this feature hasn't already been requested.
          required: true
        - label: I confirm this request is specific to the **Docker implementation**, not the core DSMR Reader software.
          required: true
