name: ðŸš¨ Issue Report
description: Report an issue or unexpected behavior with the DSMR Reader Docker image.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Sorry to hear you're experiencing an issue! ðŸ›
        
        > [!WARNING]
        > **Important scope limitations before you submit:**
        > * This repository is strictly for the **Docker implementation** of DSMR Reader. 
        > * If your issue is a bug within the core DSMR Reader application itself (e.g., calculation errors, UI bugs), please report it to the upstream project.

  - type: dropdown
    id: language
    attributes:
      label: Language / Voertaal
      description: |
        > [!TIP]
        > *ðŸ‡¬ðŸ‡§ Unable to communicate in Dutch? Welcome anyway! Feel free to use English.*
        > *ðŸ‡³ðŸ‡± Voel je vooral vrij om in het Nederlands te communiceren, ondanks dat het project Engelstalig is.*
      options:
        - 'ðŸ‡³ðŸ‡± Nederlandstalig'
        - 'ðŸ‡¬ðŸ‡§ English'
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you meet all the following requirements before submitting.
      options:
        - label: I have read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md).
          required: true
        - label: I have checked the documentation and my problem is not mentioned there.
          required: true
        - label: I have searched the open and closed issues to ensure this bug hasn't already been reported.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the issue in 1-2 sentences.
      placeholder: "When trying to start the container / view the logs, [...] happens."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Please describe precisely what you expected to happen instead.
      placeholder: "The container should start successfully without throwing a database connection error."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Please describe precisely what is actually happening.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please describe the exact steps we need to take to reproduce the issue.
      placeholder: |
        1. Start the container with...
        2. Wait for...
        3. Observe the error...
    validations:
      required: true

  - type: textarea
    id: docker_compose
    attributes:
      label: Docker Compose Configuration
      description: Please provide your `docker-compose.yml` config or the `docker run` command you are using. **Make sure to redact passwords and secrets!**
      placeholder: Paste the output of `docker compose config` here.
      render: yaml
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Container Logs
      description: Please provide the relevant container logs.
      placeholder: Paste the output of `docker logs <container_name>` here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: System & Version Information
      description: Please provide your operating system and Docker versions.
      value: |
        * OS / Architecture (type `uname -a`): 
        * Docker version (type `docker --version`): 
        * Docker Compose version (type `docker compose version`): 
    validations:
      required: true

  - type: textarea
    id: docker_info
    attributes:
      label: Docker Info
      description: Please provide your Docker system-wide information.
      placeholder: Paste the output of the `docker info` command here.
      render: yaml
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: Please provide any additional context, alternatives considered, or screenshots that might be useful for debugging.
    validations:
      required: false
