name: 🚨 Report an issue
description: Report an issue.
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Issue
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Which version has the issue?
      placeholder: "xirixiz/dsmr-reader-docker:"
      description: >
        Can be found in the About section.
  - type: input
    attributes:
      label: What was the last working version?
      placeholder: "xirixiz/dsmr-reader-docker:"
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    attributes:
      label: What type of installation are you running (architecture)?
      description: >
        If known, otherwise leave blank.
      options:
        - AMD64
        - ARM64
        - ARM
        - Other
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
