#!/command/with-contenv bash
# shellcheck shell=bash
# shellcheck source=/usr/local/lib/s6-functions.sh

set -euo pipefail
IFS=$'\n\t'

. /usr/local/lib/s6-functions.sh
_load_s6_vars



#---------------------------------------------------------------------------------------------------------------------------
# MAIN EXECUTION
#---------------------------------------------------------------------------------------------------------------------------
function main() {
    [[ "${DSMRREADER_CONTAINER_DEBUG}" == "true" ]] && set -x

    CURRENT_DIR="$(dirname "$0")"
    _info "${CURRENT_DIR} | Starting"

}

main "$@"
