#!/command/with-contenv bash
# shellcheck shell=bash
# shellcheck source=/usr/local/lib/s6-functions.sh

set -euo pipefail
IFS=$'\n\t'

. /usr/local/lib/s6-functions.sh
_load_s6_vars

function _init_start_detect_architecture() {
    local arch longbit
    arch="$(uname -m)"
    longbit="$(getconf LONG_BIT)"

    case "${arch}" in
        x86_64)
            if [[ "${longbit}" == "32" ]]; then
                _info "${CURRENT_DIR} | Architecture: X32"
            else
                _info "${CURRENT_DIR} | Architecture: X64"
            fi
            ;;
        armv7l)  _info "${CURRENT_DIR} | Architecture: ARM" ;;
        aarch64) _info "${CURRENT_DIR} | Architecture: ARM64" ;;
        *)       _info "${CURRENT_DIR} | Architecture: ${arch}" ;;
    esac
}

#---------------------------------------------------------------------------------------------------------------------------
# MAIN EXECUTION
#---------------------------------------------------------------------------------------------------------------------------
function main() {
    [[ "${DSMRREADER_CONTAINER_DEBUG}" == "true" ]] && set -x

    CURRENT_DIR="$(dirname "$0")"
    _info "${CURRENT_DIR} | Starting"
    _init_start_detect_architecture

main "$@"