#!/usr/bin/with-contenv bash

if [[ "${DATALOGGER_MODE}" = standalone ]]; then
    echo "Starting DSMR Reader - datalogger..."
    cd /app || exit
    exec /usr/local/bin/python3 -u /app/manage.py dsmr_datalogger
fi
