#!/command/with-contenv bash
# shellcheck shell=bash

function _info()  { printf "\r[ \033[00;34mINFO\033[0m ] %s\n" "$@"; }

if [[ "${DSMRREADER_OPERATION_MODE}" = standalone ]]; then
    _info "Starting DSMR Reader - datalogger..."
    cd /app || exit
    exec /command/s6-setuidgid app /opt/venv/bin/python -u /app/manage.py dsmr_datalogger
else
    _info "svc-dsmr-datalogger disabled for mode ${DSMRREADER_OPERATION_MODE}"
    exec sleep infinity
fi
