#!/command/with-contenv bash
# shellcheck shell=bash
# shellcheck source=/usr/local/lib/s6-functions.sh

. /usr/local/lib/s6-functions.sh
_load_s6_vars

function svc_dsmr_datalogger_start(){
    _info "${CURRENT_DIR} | Starting"
    cd /app || exit
    exec /command/s6-setuidgid app /opt/venv/bin/python -u /app/manage.py dsmr_datalogger
}

function main() {
    [[ "${DSMRREADER_CONTAINER_DEBUG}" == "true" ]] && set -x

    CURRENT_DIR="$(basename "$(pwd)")"
    svc_dsmr_datalogger_start
}

main "$@"