#!/command/with-contenv bash
# shellcheck shell=bash

if [[ "${DSMRREADER_OPERATION_MODE}" = standalone ]]; then
    echo "Starting DSMR Reader - datalogger..."
    cd /app || exit
    s6-setuidgid app /app/.venv/bin/python3 -u /app/manage.py dsmr_datalogger
else
    sleep infinity
fi
