#!/usr/bin/with-contenv bash

if [[ "${DATALOGGER_MODE}" = sender ]]; then
    echo "Starting DSMR Reader - remote datalogger..."
    cd /app || exit
    exec /usr/local/bin/python3 -u /app/dsmr_datalogger_api_client.py
fi
