#!/command/with-contenv bash
# shellcheck shell=bash

if [[ "${DSMRREADER_OPERATION_MODE}" = api_client ]]; then
    echo "Starting DSMR Reader - remote datalogger (api_client)..."
    cd /app || exit
    s6-setuidgid app /opt/venv/bin/python -u /app/dsmr_datalogger_api_client.py
else
    sleep infinity
fi
