#!/command/with-contenv bash
# shellcheck shell=bash

if [[ "${DSMRREADER_OPERATION_MODE}" = api_client ]]; then
    echo "Starting DSMR Reader - remote datalogger (api_client)..."
    cd /app || exit
    nice -n 5
    s6-setuidgid app
    /usr/local/bin/python3 -u /dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py
else
    sleep infinity
fi