#!/command/with-contenv bash

. /usr/local/lib/s6-functions.sh
_load_s6_vars

if [[ "${DSMRREADER_CONTAINER_RUN_MODE}" != "api_client" ]]; then
    _info "svc-dsmr-remote-datalogger disabled for mode ${DSMRREADER_CONTAINER_RUN_MODE}"
    exit 125
fi