#!/command/with-contenv bash
# shellcheck shell=bash
# shellcheck source=/usr/local/lib/s6-functions.sh

. /usr/local/lib/s6-functions.sh
_load_s6_vars

function svc_dsmr_backend_start() {
    if [[ "${DSMRREADER_CONTAINER_RUN_MODE}" = standalone || "${DSMRREADER_CONTAINER_RUN_MODE}" = api_server ]]; then
        _info "${CURRENT_DIR} | Starting"
        cd /app || exit
        exec /command/s6-setuidgid app /opt/venv/bin/python -u /app/manage.py dsmr_backend
    else
        _info "${CURRENT_DIR} disabled for mode ${DSMRREADER_CONTAINER_RUN_MODE}"
        exec sleep infinity
    fi
}

function main() {
    [[ "${DSMRREADER_CONTAINER_DEBUG}" == "true" ]] && set -x

    CURRENT_DIR="$(basename "$(pwd)")"
    svc_dsmr_backend_start
}

main "$@"