#!/usr/bin/with-contenv bash

if [[ "${DATALOGGER_MODE}" = standalone || "${DATALOGGER_MODE}" = receiver ]]; then
    echo "Starting DSMR Reader - backend..."
    cd /app || exit
    exec /usr/local/bin/python3 -u /app/manage.py dsmr_backend
fi
