#!/usr/bin/with-contenv bash

PUID=${PUID:-803}
PGID=${PGID:-803}

groupmod -o -g "${PGID}" app
usermod -o -u "${PUID}" app

echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u app)
User gid:    $(id -g app)
-------------------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
  echo 'Your DockerHost is running an outdated version of libseccomp. Search internet to fix this!'
  sleep infinity
fi

chown -R app:app /app
chown -R app:app /config
chown -R app:app /defaults
