#!/usr/bin/with-contenv bash

DUID=${DUID:-803}
DGID=${DGID:-803}

groupmod -o -g "${DGID}" app
usermod -o -u "${DUID}" app

echo "
-------------------------
User UID: $(id -u app)
User GID: $(id -g app)
-------------------------
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
  echo 'Your DockerHost is running an outdated version of libseccomp. Search internet to fix this!'
  sleep infinity
fi

usermod -a -G audio,dialout app
chown -R app:app /app
chown -R app:app /config
chown -R app:app /defaults
