#!/command/with-contenv bash
# shellcheck shell=bash

function _info()  { printf "\r[ \033[00;34mINFO\033[0m ] %s\n" "$@"; }

if [[ "${DSMRREADER_OPERATION_MODE}" = standalone || "${DSMRREADER_OPERATION_MODE}" = api_server ]]; then
    _info "Starting DSMR Reader - webinterface..."
    cd /app || exit
    exec s6-setuidgid app /opt/venv/bin/gunicorn dsmrreader.wsgi:application \
        --bind unix:/tmp/gunicorn--dsmr_webinterface.socket \
        --workers 2 \
        --threads 2 \
        --worker-class gthread \
        --timeout 120 \
        --keep-alive 5 \
        --max-requests 1000 \
        --max-requests-jitter 100 \
        --access-logfile - \
        --error-logfile -
else
    _info "svc-dsmr-webinterface disabled for mode ${DSMRREADER_OPERATION_MODE}"
    sleep infinity
fi
