name: 'build multi arch images for DSMR Reader'

on:
  push:
    branches:
      - 's6_init'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
    # login to docker hub
    - name: '⛴️ Login to DockerHub'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # checkout repo
    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '🚧 Prepare'
      id: prep
      run: |
        DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPOSITORY#*/}
        VERSION=latest
        SHORTREF=${GITHUB_SHA::8}

        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${SHORTREF}"

        if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          TAGS="$TAGS,${DOCKER_IMAGE}:latest"
        fi

        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=docker_image::${DOCKER_IMAGE}

    - name: '🚧 Setup QEMU'
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: '🚧 Set up Docker Buildx'
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: '⚙️ Build Image'
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6
        push: true
        tags: ${{ steps.prep.outputs.tags }}

    # - name: '🚀 Push'
    # - name: '🚧 Run job'
    # - name: '⚙️ Setup qus'
    # - name: '⛴️ Login to docker.io'
    # - name: '🛰️ Update manifests'
